### ISSUE TITLE
The main menu music Issue

### ISSUE THREAD

**Issue by JoelCefai** [AIESydProgYr12021/aie_cpd-karmalmao#10]
Description: 
After a game over happens, the main menu music starts all over again but it is overlapping its own audio causing the same audio playing in different times.

Priority: B

Platforms:  Windows

Build & Environment: First Build 

Reproduction: 
•Load up the build
•Play the game
-Wait until you die in the game and you return to the main menu.

**Comment by Zuesue** [comment]
this has already been covered in a previous issue

**Comment by karmalmao** [comment]
fixerd
