### ISSUE TITLE
[Bug] Volume not saving (Unsolved)

### ISSUE THREAD

**Issue by Zuesue** [AIESydProgYr12021/aie_cpd-karmalmao#6]
Description:
After playing a round of the game you will return to the main menu, where the volume will return to default instead of where the player set it.
Priority:  C ;
Platforms:  Windows
Build & Environment: Build 1
Reproduction:
-Boot up build
-Set volume to anything but default
-Play game and die
-Volume resets to default

**Comment by karmalmao** [comment]
should be saving now, added playerprefs;
